- name: Copy filebeat binary file
  copy:
    src: "{{ filebeat_rpm_source_path }}"
    dest: "{{ filebeat_rpm_destination_path }}"
  when: ansible_facts['distribution'] == 'RedHat'

- name: Copy filebeat binary file
  copy:
    src: "{{ filebeat_deb_source_path }}"
    dest: "{{ filebeat_deb_destination_path }}"
  when:
    - ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'

