- name: Copy filebeat binary file
  copy:
    src: "{{ filebeat_remote_path }}"
    dest: "/tmp/filebeat-8.11.1-x86_64.rpm"
  when: ansible_facts['distribution'] == 'RedHat'

- name: Install Filebeat Service
  shell: rpm -vi /tmp/filebeat-8.11.1-x86_64.rpm
  when: ansible_facts['distribution'] == 'RedHat'

- name: Install Filebeat Service
  shell: |
    apt update
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
    apt-get install apt-transport-https
    echo "deb https://artifacts.elastic.co/packages/8.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-8.x.list
    apt-get update && apt-get install filebeat
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'
