- name: Install Filebeat Service (Ubuntu/Debian)
  shell: dpkg -i "{{ filebeat_deb_destination_path }}"
  when: airgap_environment == "enabled"


- name: Install Filebeat Service (Ubuntu/Debian)
  shell: |
    apt update
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
    apt-get install apt-transport-https
    echo "deb https://artifacts.elastic.co/packages/8.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-8.x.list
    apt-get update && apt-get install filebeat
  when: airgap_environment == "disabled"
