- name: Copy Filebeat Installation Package
  include_tasks: copy_filebeat_package.yml
  when: airgap_environment == "enabled"

- name: Install Filebeat Service (TAR) 
  block:
    - name: Extract tar file
      shell: |
        tar -xzvf /tmp/filebeat.tar.gz -C /etc
        mv /etc/filebeat-8.13.4-linux-x86_64 /etc/filebeat
        cp -r /etc/filebeat /usr/share
        mkdir /usr/share/filebeat/bin
        cp -r /usr/share/filebeat/filebeat /usr/share/filebeat/bin
      when: filebeat_installation_by_tar_file == "enabled" 
    
    - name: Create systemd process for filebeat
      template:
        src: /ansible_playbook_filebeat/roles/filebeat/templates/filebeat.service.j2
        dest: /etc/systemd/system/filebeat.service
        owner: root
        group: root
        mode: '0644'
      when: filebeat_installation_by_tar_file == "enabled"

    - name: Reload Daemon
      shell: systemctl daemon-reload
      when: filebeat_installation_by_tar_file == "enabled"

    - name: Add /etc/filebeat to PATH in .bashrc
      lineinfile:
        path: ~/.bashrc
        line: 'export PATH="/usr/share/filebeat/bin/filebeat:$PATH"'
        insertafter: EOF
        state: present
      become: yes
      when: filebeat_installation_by_tar_file == "enabled"
  
    - name: Give permissions
      shell:  chmod 644 /etc/filebeat/filebeat.yml
      when: filebeat_installation_by_tar_file == "enabled"
 
- name: Install Filebeat Service (Redhat)
  shell: rpm -vi "{{ filebeat_rpm_destination_path }}"
  when:
    - ansible_facts['distribution'] == 'RedHat'
    - airgap_environment == "enabled"


- name: Install Filebeat Service (RedHat)
  block:
    - name: Import Elasticsearch GPG key
      shell:  rpm --import https://packages.elastic.co/GPG-KEY-elasticsearch
      when: ansible_facts['distribution'] == 'RedHat' and  airgap_environment == "disabled"

    - name: Copy elastic.repo file
      template:
        src: /ansible_playbook_filebeat/roles/filebeat/templates/elastic.repo.j2
        dest: /etc/yum.repos.d/elastic.repo
        owner: root
        group: root
        mode: '0644'
      when: ansible_facts['distribution'] == 'RedHat' and airgap_environment == "disabled"

    - name: Install Filebeat Package
      shell: yum install filebeat -y
      when: ansible_facts['distribution'] == 'RedHat' and airgap_environment == "disabled"

    - name: Enable Filebeat Service
      shell: systemctl enable filebeat
      when: ansible_facts['distribution'] == 'RedHat' and airgap_environment == "disabled"

- name: Install Filebeat Service (Ubuntu/Debian)
  shell: dpkg -i "{{ filebeat_deb_destination_path }}"
  when:
    - ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'
    - airgap_environment == "enabled"
    - filebeat_installation_by_tar_file == "disabled"


- name: Install Filebeat Service (Ubuntu/Debian)
  shell: |
    apt update
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
    apt-get install apt-transport-https
    echo "deb https://artifacts.elastic.co/packages/8.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-8.x.list
    apt-get update && apt-get install filebeat
  when: 
    - ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'
    - airgap_environment == "disabled"






