---
- name: Copy Filebeat Installation Package
  include_tasks: copy_filebeat_package.yml
  when: airgap_environment == "enabled"

- name: Install Filebeat Service using TAR file
  include_tasks: install_filebeat_TAR.yml
  when: 
    - filebeat_installation_method == "TAR"
    - airgap_environment == "enabled"
  tags:
   - filebeat
   - filebeat_install
   - filebeat_install_tar

- name: Install Filebeat Service for REDHAT
  include_tasks: install_filebeat_RPM.yml
  when: 
    - ansible_facts['distribution'] == 'RedHat'
    - filebeat_installation_method == "OS_SPEC"
  tags:
    - filebeat
    - filebeat_install
    - filebeat_install_rpm

- name: Install Filebeat Service for UBUNTU/DEBIAN
  include_tasks: install_filebeat_DEB.yml
  when: 
    - ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'
    - filebeat_installation_method == "OS_SPEC"
  tags:
    - filebeat
    - install_filebeat
    - filebeat_install_deb

- name: Enable Filebeat Service
  shell: systemctl enable filebeat
  tags:
    - filebeat
    - enable_filebeat

- name: Enable Kafka module for Filebeat
  command: filebeat modules enable kafka
  args:
    chdir: /etc/filebeat
    creates: /etc/filebeat/modules.d/kafka.yml
  tags:
    - filebeat
    - enable_kafka_module

- name: Generate Filebeat configuration
  template:
    src: /ansible_playbook_filebeat/roles/filebeat/templates/filebeat_config.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
  tags:
    - filebeat
    - generate_filebeat_config

- name: Start Filebeat service
  command: service filebeat start
  tags:
    - filebeat
    - start_filebeat

