---
- name: Install Filebeat Service
  include_tasks: install_filebeat.yml

- name: Enable Kafka module for Filebeat
  command: filebeat modules enable kafka
  args:
    creates: /etc/filebeat/modules.d/kafka.yml

- name: Generate Filebeat configuration
  template:
    src: /ansible_playbook_filebeat/roles/filebeat/templates/filebeat_config.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root

- name: Start Filebeat service
  command: service filebeat start
