---
- name: Clone CP Log Monitor Repository
  git:
    repo: git@github.com:Platformatory/kafka-cp-log-monitor.git
    dest: /root/cp_log_monitor
    clone: yes
    update: yes
  when: airgap_environment == "disabled"
  tags:
    - logstash
    - add_repository

- name: Copy CP-Log Monitor Repository
  copy:
    src: "{{ cp_log_monitor_source_path }}"
    dest: "{{ cp_log_monitor_destination_path }}"
  when: airgap_environment == "enabled"
  tags:
    - logstash
    - add_repository

- name: Setup the Assets
  shell: |
    cd "{{ cp_log_monitor_destination_path }}"/kafka-cp-log-monitor
    docker-compose up setup
    docker-compose up -d
  tags:
    - logstash
    - setup_assets

