---
- name: Install Filebeat
  hosts: all
  become: yes
  any_errors_fatal: true

  tasks:

    - name: Copy filebeat binary file
      copy:
        src: "{{ filebeat_rpm_path }}"
        dest: "/tmp/filebeat-8.11.1-x86_64.rpm"

    - name: Install Filebeat RPM
      shell: |
        wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
        apt-get install apt-transport-https
        echo "deb https://artifacts.elastic.co/packages/8.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-8.x.list
        apt-get update && apt-get install filebeat
<<<<<<< HEAD

=======
      
      
>>>>>>> d3fd4ff5f3abbeafe1b8df40e1bee13cf11f18e3
    - name: Enable Kafka module for Filebeat
      command: filebeat modules enable kafka
   
    - name: Check Kafka service status
      systemd:
        name: "{{ kafka_service_name }}"
        state: started
      register: kafka_service_status

    - name: Check zookeeper service status
      systemd:
        name: "{{ zookeeper_service_name }}"
        state: started
      register: zookeeper_service_status

    - name: Check connect service status
      systemd:
        name: "{{ connect_service_name }}"
        state: started
      register: connect_service_status


    - name: Generate Filebeat configuration
      template:
        src: /ansible_playbook_filebeat/filebeat_config.j2
        dest: /etc/filebeat/filebeat.yml
        owner: root

    - name: Start Filebeat service
      command: service filebeat start
