---
- name: Install Filebeat
  hosts: all
  become: yes
  any_errors_fatal: true

  tasks:
    - name: Install Filebeat RPM
      shell: rpm -vi "{{ filebeat_rpm_path }}"

    - name: Enable Kafka module for Filebeat
      command: filebeat modules enable kafka
   
    - name: Generate Filebeat configuration
      template:
        src: /home/cloud_user/Desktop/ansible_playbook_filebeat/filebeat_config.j2
        dest: /etc/filebeat/filebeat.yml
        owner: root

    - name: Start Filebeat service
      command: service filebeat start
