---
- name: Install Filebeat
  hosts: all
  become: yes
  any_errors_fatal: true

  tasks:

    - name: Copy filebeat binary file
      copy:
        src: "{{ filebeat_rpm_path }}"
        dest: "/tmp/filebeat-8.11.1-x86_64.rpm"

    - name: Install Filebeat RPM
      shell: rpm -vi "/tmp/filebeat-8.11.1-x86_64.rpm"

    - name: Enable Kafka module for Filebeat
      command: filebeat modules enable kafka
   
    - name: Check Kafka service status
      systemd:
        name: confluent-server
        state: started
      register: kafka_service_status   

    - name: Generate Filebeat configuration
      template:
        src: /home/cloud_user/ansible_playbook_filebeat/filebeat_config.j2
        dest: /etc/filebeat/filebeat.yml
        owner: root

    - name: Start Filebeat service
      command: service filebeat start
