---
- name: Install Filebeat
  hosts: all
  become: yes
  any_errors_fatal: true

  tasks:

    - name: Check OS distribution
      ansible.builtin.setup:
        filter: ansible_distribution    

    - name: Copy filebeat binary file
      copy:
        src: "{{ filebeat_rpm_path }}"
        dest: "/tmp/filebeat-8.11.1-x86_64.rpm"
      when: ansible_facts['distribution'] == 'RedHat' 

    - name: Install Filebeat Service
      shell: rpm -vi /tmp/filebeat-8.11.1-x86_64.rpm
      when: ansible_facts['distribution'] == 'RedHat' 

    - name: Install Filebeat Service
      shell: |
        wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
        apt-get install apt-transport-https
        echo "deb https://artifacts.elastic.co/packages/8.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-8.x.list
        apt-get update && apt-get install filebeat
      when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'

    - name: Enable Kafka module for Filebeat
      command: filebeat modules enable kafka
      args:
        creates: /etc/filebeat/modules.d/kafka.yml
   

    - name: Generate Filebeat configuration
      template:
        src: /ansible_playbook_filebeat/filebeat_config.j2
        dest: /etc/filebeat/filebeat.yml
        owner: root

    - name: Start Filebeat service
      command: service filebeat start
