---
- name: Setup Logstash and Kibana on the Kibana Server VM
  hosts: server
  become: yes
  any_errors_fatal: true

  roles:
    - logstash

- name: Setup Filebeat Service
  hosts: server
  become: yes
  any_errors_fatal: true

  roles:
    - common
    - filebeat

