---
- name: Setup Logstash and Kibana on the Kibana Server VM
  hosts: kibana_server
  become: yes
  any_errors_fatal: true

  roles:
    - logstash

- name: Setup Filebeat Service
  hosts: zookeeper:kafka_broker
  become: yes
  any_errors_fatal: true

  roles:
    - common
    - filebeat

