---
- name: Check OS distribution
  ansible.builtin.setup:
    filter: ansible_distribution

- name: Get current hostname
  shell: hostname
  register: current_hostname

- name: Debug current hostname
  ansible.builtin.debug:
    var: current_hostname.stdout
