---
- name: Check OS distribution
  ansible.builtin.setup:
    filter: ansible_distribution

- name: Get hostname
  shell: hostname
  register: current_hostname_raw

- name: Strip newline from current hostname
  set_fact:
    current_hostname: "{{ current_hostname_raw.stdout | trim }}"
